function visualizePca(transformedData, eigVectors, diagEigValues)

fig = figure();
plotAxis = axes(fig);

relativeImprotance = diagEigValues / sum(diagEigValues) * 100;

scatter(plotAxis, transformedData.PC1, transformedData.PC2, ...
    [], transformedData.Happiness, "filled");
colorbar(plotAxis)

xlabel(plotAxis, ['PC1 $= ', ...
    num2str(eigVectors(1, 1)), '\cdot x_1 + ', ...
    num2str(eigVectors(2, 1)), '\cdot x_2$', ...
    ' - importance: $', num2str(relativeImprotance(1)), '\%$'], ...
    'Interpreter', 'latex')

ylabel(plotAxis, ['PC2 $= ', ...
    num2str(eigVectors(1, 2)), '\cdot x_1 + ', ...
    num2str(eigVectors(2, 2)), '\cdot x_2$', ...
    ' - importance: $', num2str(relativeImprotance(2)), '\%$'], ...
    'Interpreter', 'latex')

end


